[pytest]
norecursedirs = env venv .venv .git __pycache__ build dist

markers =
    smoke: smoke tests
    sanity: sanity test
    str
    strtest

#Add the specified OPTS to the set of command line arguments as if they had been specified by the user.
addopts = --maxfail=5 -v
